# Generated by Django 5.2.17 on 2026-08-22 08:11

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql

_TENANT_OWNED_TABLES = [
    "inventory_stocklocation",
    "inventory_stockbalance",
    "inventory_stockmovement",
    "inventory_stockreservation",
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_productvariant_is_default'),
        ('stores', '0003_store_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'inventory_stocklocation',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalog.productvariant')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'inventory_stockbalance',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('adjustment', 'Manual adjustment'), ('reserve', 'Reserved'), ('release', 'Reservation released'), ('fulfill', 'Reservation fulfilled')], max_length=16)),
                ('delta_on_hand', models.IntegerField(default=0)),
                ('delta_reserved', models.IntegerField(default=0)),
                ('balance_on_hand_after', models.IntegerField()),
                ('balance_reserved_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='Caller-supplied correlation id (e.g. a future cart/order id) -- opaque to Inventory.', max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.stocklocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('fulfilled', 'Fulfilled')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.stocklocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_stockreservation',
            },
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_location_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('variant', 'location'), name='uniq_balance_per_variant_location'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stockbalance_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='stockbalance_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', models.F('quantity_on_hand'))), name='stockbalance_reserved_not_exceeding_on_hand'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['store', 'variant', 'location'], name='inventory_s_store_i_f4cf2b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['store', 'reference'], name='inventory_s_store_i_cc9c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['store', 'reference'], name='inventory_s_store_i_19ee5e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['store', 'status'], name='inventory_s_store_i_e2f129_idx'),
        ),
        # Every table above is a TenantOwnedModel -- RLS from day one,
        # using the NULLIF-safe helper fixed in Phase 3.
        *[
            migrations.RunSQL(*standard_tenant_policy_sql(table))
            for table in _TENANT_OWNED_TABLES
        ],
    ]
