# Generated by Django 5.2.17 on 2026-08-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Caller-supplied correlation id (e.g. a future cart/order id), opaque here.', max_length=255),
        ),
    ]
