# Generated by Django 5.2.17 on 2026-08-23 07:41

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import global_readonly_policy_sql, standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('stores', '0004_alter_store_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('locale', models.CharField(max_length=8)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notifications_notificationtemplate',
                'constraints': [models.UniqueConstraint(fields=('key', 'locale'), name='uniq_template_key_locale')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email')], max_length=32)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.eventlog')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'notifications_notificationdispatch',
                'indexes': [models.Index(fields=['store', 'status'], name='notificatio_store_i_c964f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'event', 'channel', 'notification_type'), name='uniq_dispatch_per_event_channel')],
            },
        ),
        # --- Row-Level Security --------------------------------------------
        # NotificationTemplate: platform-global (no store_id), same shape as
        # Phase 10's Plan/PlanVersion tables -- RLS enabled with ONLY an open
        # SELECT policy. app_user has no INSERT/UPDATE/DELETE policy at all,
        # so ordinary application traffic cannot write to it even though it
        # holds a blanket table-level GRANT (apps/tenancy/privileges.py).
        # Writes happen only via app_migrator (this migration, fixtures, the
        # publish_notification_template management command).
        migrations.RunSQL(*global_readonly_policy_sql("notifications_notificationtemplate")),
        # NotificationDispatch: tenant-owned, STANDARD RLS -- no exception,
        # same discipline as Phase 10's Subscription/UsageRecord/Invoice.
        migrations.RunSQL(*standard_tenant_policy_sql("notifications_notificationdispatch")),
    ]
