# Generated by Django 5.2.17 on 2026-08-22 08:49

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_store_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], max_length=16)),
                ('percentage_value', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_amount_value', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'pricing_coupon',
                'constraints': [models.UniqueConstraint(fields=('store', 'code'), name='uniq_coupon_code_per_store'), models.CheckConstraint(condition=models.Q(models.Q(('fixed_amount_value__isnull', True), ('kind', 'percentage'), ('percentage_value__isnull', False)), models.Q(('fixed_amount_value__isnull', False), ('kind', 'fixed_amount'), ('percentage_value__isnull', True)), _connector='OR'), name='coupon_value_matches_kind'), models.CheckConstraint(condition=models.Q(('percentage_value__isnull', True), models.Q(('percentage_value__gte', 1), ('percentage_value__lte', 100)), _connector='OR'), name='coupon_percentage_value_in_range')],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(help_text="ISO 3166-1 alpha-2, e.g. 'SA'.", max_length=2)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'pricing_taxrate',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('store',), name='uniq_one_active_taxrate_per_store'), models.CheckConstraint(condition=models.Q(('rate_percent__gte', 0), ('rate_percent__lte', 100)), name='taxrate_rate_percent_in_range')],
            },
        ),
        migrations.RunSQL(*standard_tenant_policy_sql("pricing_coupon")),
        migrations.RunSQL(*standard_tenant_policy_sql("pricing_taxrate")),
    ]
