# Generated by Django 5.2.17 on 2026-08-23 21:34

import apps.core.uuid7
from django.db import migrations, models

from apps.tenancy.rls import platform_admin_only_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user_id', models.UUIDField()),
                ('actor_email', models.EmailField(help_text='Denormalized at write time -- readable without a second cross-role join, and stable even if the actor account is later renamed.', max_length=254)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(db_index=True, max_length=50)),
                ('target_id', models.UUIDField()),
                ('store_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Safe, non-secret context only -- never tokens/passwords/payment data.')),
            ],
            options={
                'db_table': 'platform_admin_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='platform_ad_target__dec559_idx'), models.Index(fields=['store_id', '-created_at'], name='platform_ad_store_i_ad3a73_idx')],
            },
        ),
        # --- Row-Level Security --------------------------------------------
        # `platform_admin_only_policy_sql`: RLS enabled with ZERO policies
        # for any command -- not even SELECT. `app_user` (and every other
        # non-BYPASSRLS role) is fully locked out of this table no matter
        # what table-level GRANT it might hold. Only `app_platform_admin`
        # (BYPASSRLS, infra/postgres/init/01-roles.sh) can touch it, and
        # then only for the commands apps/platform_admin/privileges.py
        # actually GRANTs (SELECT + INSERT -- audit logs are append-only,
        # no UPDATE/DELETE grant exists at all). See
        # apps/platform_admin/tests/test_audit_log.py.
        migrations.RunSQL(*platform_admin_only_policy_sql("platform_admin_auditlog")),
    ]
