# Generated by Django 5.2.17 on 2026-08-23 12:33

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import global_readonly_policy_sql, standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_alter_store_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'themes_theme',
            },
        ),
        migrations.CreateModel(
            name='ThemeVersion',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='themes.theme')),
            ],
            options={
                'db_table': 'themes_themeversion',
            },
        ),
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('default_settings', models.JSONField(default=dict)),
                ('preview_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('theme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='themes.themeversion')),
            ],
            options={
                'db_table': 'themes_themepreset',
            },
        ),
        migrations.CreateModel(
            name='StoreThemeConfig',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(default=dict)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_configs', to='themes.themepreset')),
                ('theme_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_configs', to='themes.themeversion')),
            ],
            options={
                'db_table': 'themes_storethemeconfig',
            },
        ),
        migrations.AddConstraint(
            model_name='themeversion',
            constraint=models.UniqueConstraint(fields=('theme', 'version_number'), name='uniq_version_number_per_theme'),
        ),
        migrations.AddConstraint(
            model_name='themeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('theme',), name='uniq_current_version_per_theme'),
        ),
        migrations.AddConstraint(
            model_name='themepreset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_theme_preset'),
        ),
        migrations.AddConstraint(
            model_name='storethemeconfig',
            constraint=models.UniqueConstraint(fields=('store',), name='uniq_one_theme_config_per_store'),
        ),
        # --- Row-Level Security --------------------------------------------
        # Theme/ThemeVersion/ThemePreset: platform-global (no store_id at
        # all) -- approved Theme/Template decision, same shape as
        # subscriptions.Plan/notifications.NotificationTemplate.
        # `global_readonly_policy_sql` enables RLS with ONLY an open SELECT
        # policy; `app_user` has no matching INSERT/UPDATE/DELETE policy,
        # so PostgreSQL denies every write from ordinary application traffic
        # even though `app_user` also holds a blanket table-level GRANT for
        # all four verbs (apps/tenancy/privileges.py's post_migrate hook) --
        # RLS is the actual boundary, not the GRANT's absence. Writes
        # happen only via `app_migrator` (this migration, the seed
        # migration, the publish_theme_version/publish_theme_preset
        # management commands).
        migrations.RunSQL(*global_readonly_policy_sql("themes_theme")),
        migrations.RunSQL(*global_readonly_policy_sql("themes_themeversion")),
        migrations.RunSQL(*global_readonly_policy_sql("themes_themepreset")),
        # StoreThemeConfig: tenant-owned, STANDARD RLS -- no exception,
        # same discipline as Subscription/NotificationDispatch.
        migrations.RunSQL(*standard_tenant_policy_sql("themes_storethemeconfig")),
    ]
