# Generated by Django 5.2.17 on 2026-08-20 13:51

import apps.core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_id', 'event_type', '-created_at'], name='core_eventl_store_i_29db28_idx')],
            },
        ),
    ]
