# Generated by Django 5.2.17 on 2026-08-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
