# Generated by Django 5.2.17 on 2026-08-22 08:49

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_productvariant_is_default'),
        ('pricing', '0001_initial'),
        ('stores', '0003_store_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_amount', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('tax_amount', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.coupon')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'carts_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'carts_cartitem',
                'constraints': [models.UniqueConstraint(fields=('cart', 'variant'), name='uniq_one_line_per_variant'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cartitem_quantity_positive')],
            },
        ),
        migrations.RunSQL(*standard_tenant_policy_sql("carts_cart")),
        migrations.RunSQL(*standard_tenant_policy_sql("carts_cartitem")),
    ]
