# Generated by Django 5.2.17 on 2026-08-22 09:56

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('catalog', '0002_alter_productvariant_is_default'),
        ('shipping', '0001_initial'),
        ('stores', '0003_store_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment')], default='pending_payment', max_length=24)),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'Unfulfilled')], default='unfulfilled', max_length=24)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_amount', models.PositiveIntegerField()),
                ('discount_amount', models.PositiveIntegerField()),
                ('tax_amount', models.PositiveIntegerField()),
                ('shipping_amount', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('shipping_address', models.JSONField()),
                ('shipping_method_name_snapshot', models.CharField(max_length=255)),
                ('coupon_code_snapshot', models.CharField(blank=True, max_length=64)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'orders_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_name_snapshot', models.CharField(max_length=255)),
                ('variant_sku_snapshot', models.CharField(max_length=64)),
                ('variant_options_snapshot', models.JSONField(blank=True, default=list)),
                ('unit_price_amount', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'orders_orderitem',
            },
        ),
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'orders_ordernumbersequence',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('shipping_method_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('shipping_amount_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='carts.cart')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping.shippingmethod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'orders_checkoutsession',
                'indexes': [models.Index(fields=['store', 'expires_at'], name='orders_chec_store_i_155ac2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('cart',), name='uniq_one_active_checkout_session_per_cart')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'orders_idempotencykey',
                'constraints': [models.UniqueConstraint(fields=('store', 'key'), name='uniq_idempotency_key_per_store')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', 'created_at'], name='orders_orde_store_i_f84db8_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('store', 'number'), name='uniq_order_number_per_store'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orderitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='ordernumbersequence',
            constraint=models.UniqueConstraint(fields=('store',), name='uniq_one_sequence_per_store'),
        ),
        migrations.RunSQL(*standard_tenant_policy_sql("orders_order")),
        migrations.RunSQL(*standard_tenant_policy_sql("orders_orderitem")),
        migrations.RunSQL(*standard_tenant_policy_sql("orders_ordernumbersequence")),
        migrations.RunSQL(*standard_tenant_policy_sql("orders_checkoutsession")),
        migrations.RunSQL(*standard_tenant_policy_sql("orders_idempotencykey")),
    ]
