# Generated by Django 5.2.17 on 2026-08-22 14:38

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import global_readonly_policy_sql, standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_alter_store_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('grace_period_days', models.PositiveIntegerField(default=3)),
                ('is_default_trial', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subscriptions_plan',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_trial', True)), fields=('is_default_trial',), name='uniq_default_trial_plan')],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('price_monthly', models.PositiveIntegerField()),
                ('price_yearly', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('is_current', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions_planversion',
            },
        ),
        migrations.CreateModel(
            name='PlanVersionFeature',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_key', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.planversion')),
            ],
            options={
                'db_table': 'subscriptions_planversionfeature',
            },
        ),
        migrations.CreateModel(
            name='PlanVersionQuota',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_key', models.CharField(max_length=64)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('overage_policy', models.CharField(choices=[('block', 'Block')], default='block', max_length=16)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='subscriptions.planversion')),
            ],
            options={
                'db_table': 'subscriptions_planversionquota',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='trialing', max_length=16)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=8)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('past_due_since', models.DateTimeField(blank=True, null=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.planversion')),
                ('scheduled_plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_subscriptions', to='subscriptions.planversion')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'subscriptions_subscription',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('void', 'Void')], default='open', max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.planversion')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscriptions_invoice',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_key', models.CharField(max_length=64)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'subscriptions_usagerecord',
            },
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_number'), name='uniq_version_number_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('plan',), name='uniq_current_version_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planversionfeature',
            constraint=models.UniqueConstraint(fields=('plan_version', 'feature_key'), name='uniq_feature_per_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='planversionquota',
            constraint=models.UniqueConstraint(fields=('plan_version', 'quota_key'), name='uniq_quota_per_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('store',), name='uniq_one_subscription_per_store'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store', 'status'], name='subscriptio_store_i_d74c95_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['store', 'quota_key', 'period_end'], name='subscriptio_store_i_dcecf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('store', 'quota_key', 'period_start', 'period_end'), name='uniq_usage_record_per_period'),
        ),
        # --- Row-Level Security --------------------------------------------
        # Plan/PlanVersion/PlanVersionFeature/PlanVersionQuota: platform-
        # global (no store_id at all) -- approved architecture decision 1.
        # `global_readonly_policy_sql` enables RLS with ONLY an open SELECT
        # policy; `app_user` has no matching INSERT/UPDATE/DELETE policy on
        # these tables, so PostgreSQL denies every write from ordinary
        # application traffic even though `app_user` also holds a blanket
        # table-level GRANT for all four verbs (apps/tenancy/privileges.py's
        # post_migrate hook) -- RLS is the actual boundary, not the GRANT's
        # absence. Writes happen only via `app_migrator` (this migration,
        # future migrations, fixtures, Django admin). See
        # apps/subscriptions/tests/test_plan_rls.py for the required proof
        # (SELECT works, INSERT/UPDATE/DELETE are all rejected, tenant
        # context has no effect either way on these tables).
        migrations.RunSQL(*global_readonly_policy_sql("subscriptions_plan")),
        migrations.RunSQL(*global_readonly_policy_sql("subscriptions_planversion")),
        migrations.RunSQL(*global_readonly_policy_sql("subscriptions_planversionfeature")),
        migrations.RunSQL(*global_readonly_policy_sql("subscriptions_planversionquota")),
        # Subscription/UsageRecord/Invoice: tenant-owned, STANDARD RLS --
        # approved architecture decision: no RLS-exempt exception for
        # billing data (unlike apps.core.EventLog), full isolation like
        # every other TenantOwnedModel.
        migrations.RunSQL(*standard_tenant_policy_sql("subscriptions_subscription")),
        migrations.RunSQL(*standard_tenant_policy_sql("subscriptions_usagerecord")),
        migrations.RunSQL(*standard_tenant_policy_sql("subscriptions_invoice")),
    ]
