# Generated by Django 5.2.17 on 2026-08-27 11:58

import apps.core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_default_trial_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCheckoutSession',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_preset_id', models.UUIDField(blank=True, null=True)),
                ('checkout_status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_payment', 'Ready for payment'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('payment_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_started', max_length=16)),
                ('provisioning_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('provisioning', 'Provisioning'), ('provisioned', 'Provisioned'), ('failed', 'Failed')], default='not_started', max_length=16)),
                ('business_info_draft', models.JSONField(blank=True, null=True)),
                ('store_name_draft', models.CharField(blank=True, default='', max_length=255)),
                ('store_slug_draft', models.SlugField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='subscriptions.planversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_subscriptioncheckoutsession',
                'constraints': [models.UniqueConstraint(condition=models.Q(('checkout_status__in', ['draft', 'ready_for_payment'])), fields=('user',), name='uniq_active_checkout_session_per_user')],
            },
        ),
    ]
