# Generated by Django 5.2.17 on 2026-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_seed_paid_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncheckoutsession',
            name='checkout_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_for_payment', 'Ready for payment'), ('awaiting_business_info', 'Awaiting business info'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='draft', max_length=24),
        ),
    ]
