# Generated by Django 5.2.17 on 2026-08-27 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptioncheckoutsession_checkout_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptioncheckoutsession',
            name='uniq_active_checkout_session_per_user',
        ),
        migrations.AddConstraint(
            model_name='subscriptioncheckoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_status__in', ['draft', 'ready_for_payment', 'awaiting_business_info'])), fields=('user',), name='uniq_active_checkout_session_per_user'),
        ),
    ]
