# Generated by Django 5.2.17 on 2026-08-27 14:49

import apps.core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_subscriptioncheckoutsession_uniq_active_checkout_session_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentIntent',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=64)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'subscriptions_subscriptionpaymentintent',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions_subscriptionwebhookevent',
            },
        ),
        migrations.RemoveConstraint(
            model_name='subscriptioncheckoutsession',
            name='uniq_active_checkout_session_per_user',
        ),
        migrations.AlterField(
            model_name='subscriptioncheckoutsession',
            name='checkout_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_for_payment', 'Ready for payment'), ('payment_pending', 'Payment pending'), ('payment_failed', 'Payment failed'), ('awaiting_business_info', 'Awaiting business info'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='draft', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncheckoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_status__in', ['draft', 'ready_for_payment', 'payment_pending', 'payment_failed', 'awaiting_business_info'])), fields=('user',), name='uniq_active_checkout_session_per_user'),
        ),
        migrations.AddField(
            model_name='subscriptionpaymentintent',
            name='checkout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='subscriptions.subscriptioncheckoutsession'),
        ),
        migrations.AddField(
            model_name='subscriptionwebhookevent',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='subscriptions.subscriptionpaymentintent'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpaymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'processing'])), fields=('checkout_session',), name='uniq_active_payment_intent_per_checkout_session'),
        ),
    ]
