# Generated by Django 5.2.17 on 2026-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='True only for the auto-created variant of a simple (option-less) product.'),
        ),
    ]
