# Generated by Django 5.2.17 on 2026-08-24 07:31

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_productvariant_is_default'),
        ('stores', '0005_store_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider_key', models.CharField(choices=[('mock', 'Mock (demo data)')], default='mock', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('pricing_strategy', models.CharField(choices=[('margin_percent', 'Margin %'), ('markup_percent', 'Markup %'), ('fixed', 'Fixed price')], default='markup_percent', max_length=16)),
                ('pricing_value', models.PositiveIntegerField(default=50)),
                ('min_profit_amount', models.PositiveIntegerField(default=0, help_text='Minor units. Suggested price never yields less profit than this.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'suppliers_supplier',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('cost_amount', models.PositiveIntegerField(help_text='Minor units.')),
                ('currency', models.CharField(max_length=3)),
                ('supplier_stock', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('imported', 'Imported'), ('ignored', 'Ignored')], default='staged', max_length=16)),
                ('imported_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'suppliers_supplierproduct',
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_supplier_name_per_store'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['store', 'supplier', 'status'], name='suppliers_s_store_i_408e83_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'external_id'), name='uniq_supplier_product_external_id'),
        ),
        # --- Row-Level Security --------------------------------------------
        # Standard tenant isolation -- both models are ordinary
        # TenantOwnedModels, same as every other domain app.
        migrations.RunSQL(*standard_tenant_policy_sql("suppliers_supplier")),
        migrations.RunSQL(*standard_tenant_policy_sql("suppliers_supplierproduct")),
    ]
