# Generated by Django 5.2.17 on 2026-08-20 14:38

import apps.core.uuid7
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_passwordresettoken',
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], max_length=16)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('removed', 'Removed')], default='active', max_length=16)),
                ('extra_permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Permission keys granted on top of the role's base set.", size=None)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_storemembership',
                'constraints': [models.UniqueConstraint(fields=('store', 'user'), name='uniq_store_membership_per_user')],
            },
        ),
        # First real exercise of Phase 1's standard_tenant_policy_sql
        # helper (apps/tenancy/rls.py) -- StoreMembership doesn't need
        # StoreDomain's open-SELECT exception (nothing needs to read
        # membership rows before a tenant is known), so it gets the plain
        # fully-restricted policy every ordinary TenantOwnedModel should
        # use. `PasswordResetToken` deliberately has NO RLS: it isn't
        # tenant-owned at all (scoped by `user`, a platform-wide
        # identity), same reasoning as accounts_platformuser in Phase 1.
        migrations.RunSQL(
            *standard_tenant_policy_sql("accounts_storemembership"),
        ),
    ]
