# Generated by Django 5.2.17 on 2026-08-22 09:22

import apps.core.uuid7
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_store_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text="ISO 3166-1 alpha-2 codes. Empty means 'matches any country' (a catch-all zone).", size=None)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('postal_patterns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text="Postal-code PREFIXES (e.g. '11' matches any code starting with '11').", size=None)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'shipping_shippingzone',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('flat', 'Flat rate'), ('free', 'Free shipping'), ('weight_based', 'Weight based'), ('price_based', 'Order value based'), ('carrier_calculated', 'Carrier calculated')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone')),
            ],
            options={
                'db_table': 'shipping_shippingmethod',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_value', models.PositiveIntegerField(blank=True, null=True)),
                ('max_value', models.PositiveIntegerField(blank=True, null=True)),
                ('price_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'shipping_shippingrate',
                'ordering': ['min_value'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_value__isnull', True), ('min_value__isnull', True), ('max_value__gte', models.F('min_value')), _connector='OR'), name='shippingrate_max_not_below_min')],
            },
        ),
        migrations.RunSQL(*standard_tenant_policy_sql("shipping_shippingzone")),
        migrations.RunSQL(*standard_tenant_policy_sql("shipping_shippingmethod")),
        migrations.RunSQL(*standard_tenant_policy_sql("shipping_shippingrate")),
    ]
