# Generated by Django 5.2.17 on 2026-08-22 12:38

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import standard_tenant_policy_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('stores', '0003_store_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProviderConfig',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.CharField(max_length=32)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=8)),
                ('is_enabled', models.BooleanField(default=True)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('credentials_hint', models.CharField(blank=True, max_length=32)),
                ('webhook_secret_encrypted', models.TextField(blank=True)),
                ('public_metadata', models.JSONField(blank=True, default=dict)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'payments_storeproviderconfig',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('state', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='processing', max_length=16)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('retryable', models.BooleanField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payments.storeproviderconfig')),
            ],
            options={
                'db_table': 'payments_paymentintent',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('signature_valid', models.BooleanField()),
                ('payload_redacted', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='payments.storeproviderconfig')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'payments_webhookevent',
            },
        ),
        migrations.CreateModel(
            name='PaymentIdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'payments_paymentidempotencykey',
                'constraints': [models.UniqueConstraint(fields=('store', 'key'), name='uniq_payment_idempotency_key_per_store')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('authorize', 'Authorize'), ('capture', 'Capture'), ('refund', 'Refund'), ('void', 'Void')], max_length=16)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('raw_response_redacted', models.JSONField(blank=True, default=dict)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentintent')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'payments_paymenttransaction',
                'indexes': [models.Index(fields=['store', 'intent'], name='payments_pa_store_i_4432e2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='storeproviderconfig',
            constraint=models.UniqueConstraint(fields=('store', 'provider_key'), name='uniq_provider_config_per_store'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['store', 'state', 'updated_at'], name='payments_pa_store_i_4bb338_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'processing')), fields=('order',), name='uniq_one_processing_payment_intent_per_order'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider_config', 'external_id'), name='uniq_event_per_provider_config'),
        ),
        migrations.RunSQL(*standard_tenant_policy_sql("payments_storeproviderconfig")),
        migrations.RunSQL(*standard_tenant_policy_sql("payments_paymentintent")),
        migrations.RunSQL(*standard_tenant_policy_sql("payments_webhookevent")),
        migrations.RunSQL(*standard_tenant_policy_sql("payments_paymentidempotencykey")),
        migrations.RunSQL(*standard_tenant_policy_sql("payments_paymenttransaction")),
    ]
