# Generated by Django 5.2.17 on 2026-08-20 13:51

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending', max_length=16)),
            ],
            options={
                'db_table': 'stores_store',
                'indexes': [models.Index(fields=['status'], name='stores_stor_status_d56e36_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreDomain',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom domain')], default='subdomain', max_length=16)),
                ('is_primary', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stores.store')),
            ],
            options={
                'db_table': 'stores_storedomain',
            },
        ),
        # --- Row-Level Security --------------------------------------------
        # `app_user` (the role the running application authenticates as --
        # see docs/ARCHITECTURE.md section 2.3) is NOT the owner of these
        # tables and has NOBYPASSRLS, so these policies are the real
        # enforcement boundary, not a formality. `app_migrator` (which runs
        # this migration and owns the tables) bypasses RLS by default as
        # table owner, which is fine -- migrations are schema operations,
        # not tenant data access.
        #
        # Store: hand-written policies keyed on `id`, not `store_id` -- it
        # IS the tenant root, it doesn't have one. SELECT/INSERT are open
        # (a store's name/slug/status are comparable to public
        # DNS/whois-level information, and registering a new store must be
        # possible before any tenant context exists). UPDATE/DELETE are
        # restricted to the store's own context. See apps/stores/models.py.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE stores_store ENABLE ROW LEVEL SECURITY;\n"
                "CREATE POLICY stores_store_select_open ON stores_store\n"
                "    FOR SELECT USING (true);\n"
                "CREATE POLICY stores_store_insert_open ON stores_store\n"
                "    FOR INSERT WITH CHECK (true);\n"
                "CREATE POLICY stores_store_write_self ON stores_store\n"
                "    FOR UPDATE USING (id = current_setting('app.current_store_id', true)::uuid)\n"
                "    WITH CHECK (id = current_setting('app.current_store_id', true)::uuid);\n"
                "CREATE POLICY stores_store_delete_self ON stores_store\n"
                "    FOR DELETE USING (id = current_setting('app.current_store_id', true)::uuid);"
            ),
            reverse_sql=(
                "DROP POLICY IF EXISTS stores_store_select_open ON stores_store;\n"
                "DROP POLICY IF EXISTS stores_store_insert_open ON stores_store;\n"
                "DROP POLICY IF EXISTS stores_store_write_self ON stores_store;\n"
                "DROP POLICY IF EXISTS stores_store_delete_self ON stores_store;\n"
                "ALTER TABLE stores_store DISABLE ROW LEVEL SECURITY;"
            ),
        ),
        # StoreDomain: standard tenant isolation on store_id for
        # writes, but SELECT stays open -- TenantMiddleware must be able to
        # resolve a hostname to a store *before* any tenant context exists
        # (see apps/tenancy/middleware.py). Hostnames are not secret.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE stores_storedomain ENABLE ROW LEVEL SECURITY;\n"
                "CREATE POLICY stores_storedomain_select_open ON stores_storedomain\n"
                "    FOR SELECT USING (true);\n"
                "CREATE POLICY stores_storedomain_write_self ON stores_storedomain\n"
                "    FOR INSERT WITH CHECK (store_id = current_setting('app.current_store_id', true)::uuid);\n"
                "CREATE POLICY stores_storedomain_update_self ON stores_storedomain\n"
                "    FOR UPDATE USING (store_id = current_setting('app.current_store_id', true)::uuid)\n"
                "    WITH CHECK (store_id = current_setting('app.current_store_id', true)::uuid);\n"
                "CREATE POLICY stores_storedomain_delete_self ON stores_storedomain\n"
                "    FOR DELETE USING (store_id = current_setting('app.current_store_id', true)::uuid);"
            ),
            reverse_sql=(
                "DROP POLICY IF EXISTS stores_storedomain_select_open ON stores_storedomain;\n"
                "DROP POLICY IF EXISTS stores_storedomain_write_self ON stores_storedomain;\n"
                "DROP POLICY IF EXISTS stores_storedomain_update_self ON stores_storedomain;\n"
                "DROP POLICY IF EXISTS stores_storedomain_delete_self ON stores_storedomain;\n"
                "ALTER TABLE stores_storedomain DISABLE ROW LEVEL SECURITY;"
            ),
        ),
    ]
