# Generated by Django 5.2.17 on 2026-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_null_safe_rls_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='default_currency',
            field=models.CharField(default='SAR', max_length=3),
        ),
    ]
