# Generated by Django 5.2.17 on 2026-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('read_only', 'Read-only')], default='pending', max_length=16),
        ),
    ]
