# Generated by Django 5.2.17 on 2026-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
