# Generated by Django 5.2.17 on 2026-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
