# Generated by Django 5.2.17 on 2026-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_business_category_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='business_category',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
    ]
